// User Actions
export const UserActionTypes = {
    SIGN_UP_USER: "SIGN_UP_USER",
    SIGN_UP_USER_FAIL: "SIGN_UP_USER_FAIL",
    SIGN_IN_USER: "SIGN_IN_USER",
    SIGN_IN_USER_FAIL: "SIGN_IN_USER_FAIL",
    SIGN_OUT_USER: "SIGN_OUT_USER",
    UPDATE_DOCTOR_INFO: "UPDATE_DOCTOR_INFO",
    UPDATE_DOCTOR_INFO_FAIL: "UPDATE_DOCTOR_INFO_FAIL",
    SET_LOGGED_IN: "SET_LOGGED_IN",
    SET_CURRENT_USER: "SET_CURRENT_USER",
    GET_USER: "GET_USER",
    CREATE_USER: "CREATE_USER",
    CREATE_USER_FAILED: "CREATE_USER_FAILED",
    GET_ALL_USERS_START: "GET_ALL_USERS_START",
    GET_ALL_USERS: "GET_ALL_USERS",
    GET_ALL_USERS_FAIL: "GET_ALL_USERS_FAIL",
    RESET_PASSWORD: "RESET_PASSWORD",
    RESET_PASSWORD_FAIL: "RESET_PASSWORD_FAIL",
    DELETE_USER: "DELETE_USER",
    DELETE_USER_FAIL: "DELETE_USER_FAIL",
    RESET_MESSAGES: "RESET_MESSAGES",
}

export const PatientsActionTypes =  {
    FETCH_PATIENTS_SUCCESS_START: "FETCH_PATIENTS_SUCCESS_START",
    FETCH_PATIENTS_SUCCESS: "FETCH_PATIENTS_SUCCESS",
    FETCH_PATIENTS_FAIL: "FETCH_PATIENTS_FAIL",
    CREATE_PATIENT_SUCCESS: "CREATE_PATIENT_SUCCESS",
    CREATE_PATIENT_FAIL: "CREATE_PATIENT_FAIL",
    DELETE_PATIENT_SUCCESS: "DELETE_PATIENT_SUCCESS",
    DELETE_PATIENT_FAIL: "DELETE_PATIENT_FAIL",
    UPDATE_PATIENT_SUCCESS: "UPDATE_PATIENT_SUCCESS",
    UPDATE_PATIENT_FAIL: "UPDATE_PATIENT_FAIL",
    RESET_MESSAGES: "RESET_MESSAGES"
}

export const UnassignedStudiesActionTypes =  {
    FETCH_UNASSIGNED_STUDIES_SUCCESS_START: "FETCH_UNASSIGNED_STUDIES_SUCCESS_START",
    FETCH_UNASSIGNED_STUDIES_SUCCESS: "FETCH_UNASSIGNED_STUDIES_SUCCESS",
    FETCH_UNASSIGNED_STUDIES_FAIL: "FETCH_UNASSIGNED_STUDIES_FAIL"
}